package json;

public enum JSONReadFeature {
    ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER,
    ALLOW_SINGLE_QUOTES,
    ALLOW_UNESCAPED_CONTROL_CHARS,
    ALLOW_UNQUOTED_FIELD_NAMES,
    ALLOW_MISSING_VALUES,
    ALLOW_TRAILING_COMMA
}
