package json;

public enum JSONReadFeature {
    JAVA_COMMENTS,
    INVALID_ESCAPES,
    SINGLE_QUOTES,
    STRING_CONTROL_CHARS,
    UNQUOTED_FIELD_NAMES,
    ARRAY_MISSING_VALUES,
    TRAILING_COMMA,
    NAN_INF_NUMBERS,
    CASE_INSENSITIVE
    // ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS, ALLOW_LEADING_PLUS_SIGN_FOR_NUMBERS, ALLOW_LEADING_ZEROS_FOR_NUMBERS,
    // ALLOW_TRAILING_DECIMAL_POINT_FOR_NUMBERS
}
