package json;

public enum JSONReadFeature {
    ALLOW_JAVA_COMMENTS,
    INVALID_ESCAPES,
    ALLOW_SINGLE_QUOTES,
    ALLOW_UNESCAPED_CONTROL_CHARS,
    ALLOW_UNQUOTED_FIELD_NAMES,
    ALLOW_MISSING_VALUES,
    ALLOW_TRAILING_COMMA,
    ALLOW_NON_NUMERIC_NUMBERS,
    CASE_INSENSITIVE
    // ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS, ALLOW_LEADING_PLUS_SIGN_FOR_NUMBERS, ALLOW_LEADING_ZEROS_FOR_NUMBERS,
    // ALLOW_TRAILING_DECIMAL_POINT_FOR_NUMBERS
}
